# Gram-Schmidt Orthogonalization
It is possible to convert a set of independent vectors into a set of orthogonal vectors
that spans the same vector space. The standard procedure to accomplish
this is called Gram-Schmidt orthogonalization.This notebook includes numerical examples of Gram-Schmidt orthogonalization.

Farhad Kamangar  Sept. 2018

## Gram-Schmidt Orthogonalization Procedure

Given $n$ independent vectors $y_1,y_2,...,y_n$ , which span an $n$ dimensional vector space and are not necessarily orthogonal to each other, we want to obtain $n$ orthogonal vectors $v_1,v_2,...,v_n$ which span the same vector space.

* ** Step 1: ** Select $v_1$ to be the same as $y_1$.
* ** Step 2: ** Subtract the portion of $y_2$ which is in the direction of $v_1$. In other words find the projection of $y_2$ on $y_1$ and subtract it from $y_2$.

$$\large v_2=y_2-av_1$$
Since $v_1$ and $v_2$ should be orthogonal to each other, We need to choose $a$ such that the inner product of $v_1$ and $v_2$ be equal to 0. 
$$ (v_1,v_2)=0 $$ 

$$(v_1,y_2-av_1)=0 $$

$$ (v_1,y_2) -a(v_1,v_1)=0 $$

$$ (v_1,y_2) =a(v_1,v_1) $$

$$\large a=\frac {(v_1,y_2)}{(v_1,v_1)}$$

Generalizing this approach to the kth vector results in:

$$\huge v_k=y_k-\sum_{i=1}^{k-1} \frac{(v_i,y_k)}{(v_i,v_i)}v_i $$


## Numerical Example

In [34]:
import numpy as np
def gram_schmidt_orthogonalization(y):
    # given n basis vectors as a square matrix, this
    # function finds and returns a set of n basis vectors
    # which are orthogonal to each other and span the same 
    # vector space.
    # Each column of the y matrix represents a bsis vector
    # Farhad Kamangar Sept. 2018
    v=[]
    for k in range(len(y)):
        current_y=y[:,k]
        temp_vector=current_y
        # calculate sigma part of the equation
        for i in range(k):
            #print("i: ",i,(np.dot(v[i],current_y)/np.dot(v[i],v[i])))
            temp_vector=temp_vector-(np.dot(v[i],current_y)/np.dot(v[i],v[i]))*v[i]
        v.append(temp_vector)
    return np.transpose(np.array(v))
        
#y = np.transpose(np.array([[2,1], [1,2]]))
#v=gram_schmidt_orthogonalization(y)
#print("original basis vectors:\n ", y)
#print("After Gram_Schmidt Orthogonalization:\n",v)


#y =np.transpose( np.array([[1,2,3], [2,-1,0], [1,0,2]]))
#y =np.transpose( np.array([[1,0,2], [2,1,-1], [1,2,4]]))
#y =np.transpose( np.array([[0,1,2], [2,2,-1], [1,2,6]]))
y =np.transpose( np.array([[1,1,2], [0,2,-1], [1,2,6]]))
v=gram_schmidt_orthogonalization(y)
print("original basis vectors:\n ", y)
print("After Gram_Schmidt Orthogonalization:\n",v)

original basis vectors:
  [[ 1  0  1]
 [ 1  2  2]
 [ 2 -1  6]]
After Gram_Schmidt Orthogonalization:
 [[ 1.   0.  -1.5]
 [ 1.   2.   0.3]
 [ 2.  -1.   0.6]]
