<a href="https://colab.research.google.com/github/farhadkamangar/CSE5368/blob/master/tensorflow_multi_layer_with_graph_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from datetime import datetime

%load_ext tensorboard

In [ ]:
class FlexibleDenseLayer(tf.Module):
  def __init__(self, number_of_nodes, name=None):
    super().__init__(name=name)
    self.first_time=True
    self.number_of_nodes=number_of_nodes
    
  def calculate_output(self, x):
    if self.first_time:
      self.w = tf.Variable(tf.random.normal([x.shape[-1], self.number_of_nodes]), name='weights')
      self.b = tf.Variable(tf.zeros([self.number_of_nodes]), name='biases')
      self.first_time=False
    y = tf.matmul(x, self.w) + self.b
    # return tf.nn.hard_tanh(y)
    # return tf.nn.relu(y)
    return y

In [ ]:
class MultiLayer_NN(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

    self.layer_1 = FlexibleDenseLayer(number_of_nodes=3)
    self.layer_2 = FlexibleDenseLayer(number_of_nodes=5)

  def predict(self, x):
    x = self.layer_1.calculate_output(x)
    return self.layer_2.calculate_output(x)

my_model = MultiLayer_NN(name="the_model")

output_of_model=my_model.predict(tf.constant([[1.0, 2.0, 3.0]]))
print("Model results:", output_of_model)
print("Weights ", my_model.layer_2.w)
print("Submodules:", my_model.submodules)
for var in my_model.variables:
  print(var, "\n")

Model results: tf.Tensor([[ 3.3240354  0.         5.936384   0.         4.940175  11.829053 ]], shape=(1, 6), dtype=float32)
Weights  <tf.Variable 'weights:0' shape=(3, 6) dtype=float32, numpy=
array([[ 0.8721237 , -0.10960671,  0.96784043, -0.12975301,  1.4159669 ,
        -0.62478286],
       [-0.27331188, -0.7469185 ,  1.3878955 ,  0.7425421 ,  0.13886489,
        -0.63346016],
       [ 0.35855648, -0.23694906,  0.8342599 , -1.3569158 ,  0.49348417,
         2.5020318 ]], dtype=float32)>
Submodules: (<__main__.DenseLayer object at 0x7f1eed16c990>, <__main__.DenseLayer object at 0x7f1eed16c710>)
<tf.Variable 'biases:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)> 

<tf.Variable 'weights:0' shape=(3, 3) dtype=float32, numpy=
array([[-1.1952347 ,  1.1689026 ,  1.3443784 ],
       [ 1.5287184 , -0.7772326 , -0.01542287],
       [ 0.51341724, -1.0981852 ,  1.2464136 ]], dtype=float32)> 

<tf.Variable 'biases:0' shape=(6,) dtype=float32, numpy=array([0., 0., 0., 0.,